name: progetto_esame
description: Sito web dedicato all'arte
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  flutter_email_sender: ^5.2.0
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
  - assets/chantal.jpg
  - assets/fabrizio.jpg
  - assets/alessia.jpg
  - assets/sfondo_about_me.png
  - assets/aqua.jpeg
  - assets/barilla.jpeg
  - assets/blackwhite.png
  - assets/creation.jpg
  - assets/paint.png
  - assets/quadri.jpg
  - assets/traffico.jpeg

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/logo/logo-scheda.png"
